title: Piráti Litoměřicko
email: litomericko@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://litomericko.pirati.cz" # the base hostname & protocol for your site

administrator:
  email: mikulas.peksa@pirati.cz

markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate_path: "/aktuality/:num/"
paginate: 11

future: false

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  reports:
    output: true
    permalink: /reports/:path/
defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "people, foto"
  -


calendar:
fb: https://www.facebook.com/565612520258085/
tw: 

emptyArray: []
